### ISSUE TITLE
[BUG] `eggs update` command updates to invalid `releases` version for some imports

### ISSUE THREAD

**Issue by asos-craigmorten** [nestlandofficial/nest.land#142]
**Describe the bug**

Running the `eggs update` results in some import statements for dependencies being updated to an invalid URL where the version is set to `releases`.

Before: `export { encodeUrl } from "https://deno.land/x/encodeurl@1.0.0/mod.ts";`
After: `export { encodeUrl } from "https://deno.land/x/encodeurl@releases/mod.ts";`

**To Reproduce**

1. Create a directory / repo with a `deps.ts` file.
1. Add the following to the `deps.ts`:

    ```ts
    export { serve } from "https://deno.land/std@0.58.0/http/server.ts";
    export { Status } from "https://deno.land/std@0.56.0/http/http_status.ts";
    export { encodeUrl } from "https://deno.land/x/encodeurl@1.0.0/mod.ts";
    ```

1. Install the latest eggs CLI using `deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.1.4/mod.ts`
1. Ensure your `$PATH` is updated with the Deno bin directory.
1. Run `eggs update`.
1. Notice how the `serve` import is unchanged, the `Status` import URL is correctly updated to `@0.58.0`, and the `encodeUrl` import now has the invalid version `@releases`.

**Expected behavior**

All import statements should be upgraded properly, left alone if on latest, or left alone + warning if unable to upgrade for any reason. Invalid import URLs should not be created.

**Screenshots**

<img width="1552" alt="Screen Shot 2020-06-26 at 10 50 06" src="https://user-images.githubusercontent.com/46491566/85844575-d8e5b200-b79a-11ea-943a-a1c345121902.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - nest.land Version 0.1.4

**Additional context**

Happy to take a stab at fixing this - be nice to get involved :smile:

**Comment by oganexon** [comment]
This has been fixed in the nest release 😀
Thanks for the bug report, we haven't thought of this case. The author hasn't published any version on the repo so that's why it failed.

New behaviour:
```ts
export { serve } from "https://deno.land/std@0.58.0/http/server.ts";
export { Status } from "https://deno.land/std@0.56.0/http/http_status.ts";
export { encodeUrl } from "https://deno.land/x/encodeurl@1.0.0/mod.ts";
```
Becomes
```ts
export { serve } from "https://deno.land/std@0.58.0/http/server.ts";
export { Status } from "https://deno.land/std@0.58.0/http/http_status.ts";
export { encodeUrl } from "https://deno.land/x/encodeurl@1.0.0/mod.ts";
```

![image](https://user-images.githubusercontent.com/52361520/85847603-fe2ced00-b7a7-11ea-912f-a04133834355.png)

**Comment by tbaumer22** [comment]
@asos-craigmorten thanks so much for making this issue! Sorry it was already fixed... I suppose that is a good problem to have though :)

Keep an eye out for some more issues if you're still interested in contributing!

**Comment by asos-craigmorten** [comment]
Don't be sorry it's fixed :joy: it's awesome you're all on it 💯

**Comment by asos-craigmorten** [comment]
Don't know if the fix was released in `0.1.5` - still seeing the same issue.

But on a slightly different, but related point. Attempting to update Oak, i.e.:

```ts
export * as Oak from "https://deno.land/x/oak@v5.3.1/mod.ts";
```

Results in a downgrade to:

```ts
export * as Oak from "https://deno.land/x/oak@v4.0.0/mod.ts";
```

I am guessing that the logic is currently relying on GitHub releases given that was the last Oak release.

May I suggest we migrate to using `tags` as the basis of versioning instead given a release generally creates a tag, and afaik people tend to use tags for versions over releases? Tags are also more of a universal concept (e.g. git, not just GH). I appreciate it may not be that simple though!

**Comment by tbaumer22** [comment]
@asos-craigmorten so sorry! We ended up not pushing the updates @oganexon had made to the CLI, so this bug wasn't resolved. It'll be in the next version, which is coming very soon.

Your `tag` idea is something I think we should discuss further with @zorbyte. Any thoughts Oscar?
